# Generated by Django 3.2.7 on 2021-10-27 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaProduct',
            fields=[
                ('createdatmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.createdatmodel')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salesman', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('аниме', 'аниме'), ('боевик', 'боевик'), ('вестерн', 'вестерн'), ('военный', 'военный'), ('детектив', 'детектив'), ('документальный', 'документальный'), ('драма', 'драма'), ('исторический', 'исторический'), ('комедия', 'комедия'), ('короткометражный', 'короткометражный'), ('криминал', 'криминал'), ('мелодрама', 'мелодрама'), ('мультфильм', 'мультфильм'), ('научный', 'научный'), ('приключения', 'приключения'), ('семейный', 'семейный'), ('триллер', 'триллер'), ('ужасы', 'ужасы'), ('фантастика', 'фантастика'), ('фэнтези', 'фэнтези'), ('эротика', 'эротика')], max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/cinema_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(choices=[('RUS', 'RUS'), ('ENG', 'ENG'), ('KGZ', 'KGZ'), ('DEU', 'DEU'), ('EGY', 'EGY'), ('KAZ', 'KAZ'), ('CHN', 'CHN'), ('KOR', 'KOR'), ('TUR', 'TUR')], max_length=25)),
            ],
            bases=('main.createdatmodel', main.models.ProductInfoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CinemaProductReview',
            fields=[
                ('createdatmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.createdatmodel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/cinema_review')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinema_reviews', to=settings.AUTH_USER_MODEL)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_reviews', to='main.cinemaproduct')),
            ],
            bases=('main.createdatmodel',),
        ),
    ]
